### ISSUE TITLE
Panic on out of range cursorRow

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/terminal#29]
I can't figure out, but one of my ssh session can consistently lead to the following crash.

```
panic: runtime error: index out of range [-9]

goroutine 1060 [running]:
github.com/fyne-io/terminal.(*Terminal).handleOutputChar(0xc0055ce000, 0x61)
	/home/cedric/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230223114940-c76e408adbd3/output.go:128 +0x3be
github.com/fyne-io/terminal.(*Terminal).handleOutput(0xc0055ce000, {0xc005c56000, 0x7e, 0x0?})
	/home/cedric/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230223114940-c76e408adbd3/output.go:108 +0x4d8
github.com/fyne-io/terminal.(*Terminal).run(0xc0055ce000)
	/home/cedric/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230223114940-c76e408adbd3/term.go:243 +0x132
github.com/fyne-io/terminal.(*Terminal).RunWithConnection(0xc0055ce000, {0x1987ec0?, 0xc0059d47a0}, {0x7fabd0042438?, 0xc004f26180})
	/home/cedric/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230223114940-c76e408adbd3/term.go:273 +0xc5
```

**Comment by andydotxyz** [comment]
Looks to be resolved with latest race fixes
