### ISSUE TITLE
CTRL + "=": panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by xaionaro** [fyne-io/terminal#89]
Hello.

I use Linux with XOrg server, and if run fyneterm, select russian layout and then click combination <ctrl + equals (key "=")> then it immediately panics:
```
xaionaro@void:~$ fyneterm
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
github.com/fyne-io/terminal.(*Terminal).TypedShortcut(0xc000480000, {0xd712e0?, 0xc0022596e0?})
	/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20240628092338-cee53fe6c43c/input.go:170 +0x23b
fyne.io/fyne/v2/internal/driver/glfw.(*window).triggersShortcut.func1()
	/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/fyne.io/fyne/v2@v2.4.6-0.20240617212519-759df6f70f7e/internal/driver/glfw/window.go:907 +0x24
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(...)
	/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/fyne.io/fyne/v2@v2.4.6-0.20240617212519-759df6f70f7e/internal/driver/common/window.go:35
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1 in goroutine 1
	/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/fyne.io/fyne/v2@v2.4.6-0.20240617212519-759df6f70f7e/internal/driver/glfw/window.go:961 +0x136
```

Repro: 4/4.

This issue does not cause me any problems, decided to report just in case.

**Comment by andydotxyz** [comment]
Feel free to check out the PR @xaionaro - it should fix the issue.
